# Copyright (c) 2024 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  self:
    west-commands: scripts/west-commands.yml
    path: project

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: syver
      url-base: https://github.com/SyverHaraldsen

  projects:
    - name: nrf
      remote: syver
      repo-path: sdk-nrf
      revision: compressed-fota-t91x-partition-changes
      import: true
    - name: mcuboot
      remote: syver
      repo-path: sdk-mcuboot
      revision: bl-two-image-patch
      path: bootloader/mcuboot
