# Copyright (c) 2024 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  self:
    west-commands: scripts/west-commands.yml
    path: project

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: opt-modules
      url-base: https://github.com/SyverHaraldsen

  group-filter: [-opt]

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: e3daa6d07317a2e34a8588cd0cda8bb605017bae
      import: true
    - name: opt-modules
      remote: opt-modules
      repo-path: optional_modules
      revision: main
      import: false
      groups:
        - opt
