# Copyright (c) 2024 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  self:
    west-commands: scripts/west-commands.yml
    path: project

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: MDZM
      url-base: https://github.com/SyverHaraldsen

  group-filter: [-multi-domain-modules]

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: 810b478aacde5d612130c32c9f0be52ca49aee2a
      import: true
    - name: Multi-Domain-ZBus-Modules
      remote: MDZM
      repo-path: Multi-Domain-ZBus-Modules
      path: project/multi-domain-modules
      revision: main
      import: false
      groups:
        - multi-domain-modules
